# Generated by Django 4.0.3 on 2022-03-08 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('imdb', models.URLField(blank=True)),
                ('ratings', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('watched', models.BooleanField(default=False)),
                ('date_watched', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
